version: '3.4'

services:
  device:
    image: azureiot/device
    build:
      context: .
      dockerfile: Device/Dockerfile
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
  backend:
    image: azureiot/backend
    build:
      context: .
      dockerfile: Backend/Dockerfile
    volumes:
      - ~/.vsdbg:/remote_debugger:rw