version: '3.4'

services:
  device:
    image: ${DEVICE_IMAGE_NAME}
    build:
      context: .
      dockerfile: Device/Dockerfile
    environment:
      ENVIRONMENT_TAG: ${ENVIRONMENT_TAG}
      ENROLLMENT_ID: ${ENROLLMENT_ID}
      ENROLLMENT_PRIMARY_KEY: ${ENROLLMENT_PRIMARY_KEY}
      ENROLLMENT_ID_SCOPE: ${ENROLLMENT_ID_SCOPE}

  backend:
    image: ${BACKEND_IMAGE_NAME}
    build:
      context: .
      dockerfile: Backend/Dockerfile
    environment:
      ENVIRONMENT_TAG: ${ENVIRONMENT_TAG}
      BACKEND_IOT_HUB_CONNECTION_STRING: ${BACKEND_IOT_HUB_CONNECTION_STRING}
      BACKEND_IOT_HUB_EVENT_HUB_ENDPOINT_NAME: ${BACKEND_IOT_HUB_EVENT_HUB_ENDPOINT_NAME}